/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'

const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/_authenticated/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/edit-profile': typeof AuthenticatedEditProfileRoute
}
export interface FileRoutesByTo {
  '/edit-profile': typeof AuthenticatedEditProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/edit-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/edit-profile'
  id: '__root__' | '/_authenticated/edit-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
