/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'

const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/_authenticated/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRoutesByTo {
  '/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/overview'
  id: '__root__' | '/_authenticated/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
