/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedPageVisitRouteImport } from './routes/_authenticated/page-visit'

const AuthenticatedPageVisitRoute = AuthenticatedPageVisitRouteImport.update({
  id: '/_authenticated/page-visit',
  path: '/page-visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/page-visit': typeof AuthenticatedPageVisitRoute
}
export interface FileRoutesByTo {
  '/page-visit': typeof AuthenticatedPageVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/page-visit': typeof AuthenticatedPageVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/page-visit'
  fileRoutesByTo: FileRoutesByTo
  to: '/page-visit'
  id: '__root__' | '/_authenticated/page-visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPageVisitRoute: typeof AuthenticatedPageVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/page-visit': {
      id: '/_authenticated/page-visit'
      path: '/page-visit'
      fullPath: '/page-visit'
      preLoaderRoute: typeof AuthenticatedPageVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPageVisitRoute: AuthenticatedPageVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
