/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedPaymentAdminRouteImport } from './routes/_authenticated/payment-admin'

const AuthenticatedPaymentAdminRoute =
  AuthenticatedPaymentAdminRouteImport.update({
    id: '/_authenticated/payment-admin',
    path: '/payment-admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/payment-admin': typeof AuthenticatedPaymentAdminRoute
}
export interface FileRoutesByTo {
  '/payment-admin': typeof AuthenticatedPaymentAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/payment-admin': typeof AuthenticatedPaymentAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/payment-admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/payment-admin'
  id: '__root__' | '/_authenticated/payment-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPaymentAdminRoute: typeof AuthenticatedPaymentAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/payment-admin': {
      id: '/_authenticated/payment-admin'
      path: '/payment-admin'
      fullPath: '/payment-admin'
      preLoaderRoute: typeof AuthenticatedPaymentAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPaymentAdminRoute: AuthenticatedPaymentAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
