/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedUserListRouteImport } from './routes/_authenticated/user-list'

const AuthenticatedUserListRoute = AuthenticatedUserListRouteImport.update({
  id: '/_authenticated/user-list',
  path: '/user-list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/user-list': typeof AuthenticatedUserListRoute
}
export interface FileRoutesByTo {
  '/user-list': typeof AuthenticatedUserListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/user-list': typeof AuthenticatedUserListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/user-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/user-list'
  id: '__root__' | '/_authenticated/user-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedUserListRoute: typeof AuthenticatedUserListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/user-list': {
      id: '/_authenticated/user-list'
      path: '/user-list'
      fullPath: '/user-list'
      preLoaderRoute: typeof AuthenticatedUserListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedUserListRoute: AuthenticatedUserListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
