/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'

const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/_authenticated/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/help': typeof AuthenticatedHelpRoute
}
export interface FileRoutesByTo {
  '/help': typeof AuthenticatedHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/help': typeof AuthenticatedHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/help'
  fileRoutesByTo: FileRoutesByTo
  to: '/help'
  id: '__root__' | '/_authenticated/help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
